keytool -export -keystore cacerts -rfc -storepass changeit -alias digicertassuredidrootca -file digicertassuredidrootca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias comodorsaca -file comodorsaca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias thawtepremiumserverca -file thawtepremiumserverca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias swisssignplatinumg2ca -file swisssignplatinumg2ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias swisssignsilverg2ca -file swisssignsilverg2ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias equifaxsecureebusinessca1 -file equifaxsecureebusinessca1.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias securetrustca -file securetrustca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias utnuserfirstclientauthemailca -file utnuserfirstclientauthemailca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias affirmtrustnetworkingca -file affirmtrustnetworkingca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias entrustevca -file entrustevca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias utnuserfirsthardwareca -file utnuserfirsthardwareca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias globalsigneccrootcar5 -file globalsigneccrootcar5.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias globalsigneccrootcar4 -file globalsigneccrootcar4.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias certumca -file certumca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias addtrustclass1ca -file addtrustclass1ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias entrustrootcag2 -file entrustrootcag2.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias equifaxsecureca -file equifaxsecureca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias quovadisrootca3 -file quovadisrootca3.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias quovadisrootca2 -file quovadisrootca2.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias swisscomrootca2 -file swisscomrootca2.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias digicerthighassuranceevrootca -file digicerthighassuranceevrootca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias equifaxsecureglobalebusinessca1 -file equifaxsecureglobalebusinessca1.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias geotrustuniversalca -file geotrustuniversalca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias verisignclass3ca -file verisignclass3ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias thawteprimaryrootcag3 -file thawteprimaryrootcag3.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias thawteprimaryrootcag2 -file thawteprimaryrootcag2.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias deutschetelekomrootca2 -file deutschetelekomrootca2.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias buypassclass3ca -file buypassclass3ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias utnuserfirstobjectca -file utnuserfirstobjectca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias geotrustprimaryca -file geotrustprimaryca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias buypassclass2ca -file buypassclass2ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias baltimorecodesigningca -file baltimorecodesigningca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias verisignclass1ca -file verisignclass1ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias baltimorecybertrustca -file baltimorecybertrustca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias starfieldclass2ca -file starfieldclass2ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias actalisauthenticationrootca -file actalisauthenticationrootca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias camerfirmachamberscommerceca -file camerfirmachamberscommerceca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias ttelesecglobalrootclass3ca -file ttelesecglobalrootclass3ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias verisignclass3g5ca -file verisignclass3g5ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias ttelesecglobalrootclass2ca -file ttelesecglobalrootclass2ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias verisignclass3g4ca -file verisignclass3g4ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias verisignclass3g3ca -file verisignclass3g3ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias xrampglobalca -file xrampglobalca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias entrustrootcaec1 -file entrustrootcaec1.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias certplusclass3pprimaryca -file certplusclass3pprimaryca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias certumtrustednetworkca -file certumtrustednetworkca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias verisignclass3g2ca -file verisignclass3g2ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias globalsignr3ca -file globalsignr3ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias utndatacorpsgcca -file utndatacorpsgcca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias secomscrootca2 -file secomscrootca2.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias gtecybertrustglobalca -file gtecybertrustglobalca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias secomscrootca1 -file secomscrootca1.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias affirmtrustcommercialca -file affirmtrustcommercialca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias verisignuniversalrootca -file verisignuniversalrootca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias globalsignr2ca -file globalsignr2ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias certplusclass2primaryca -file certplusclass2primaryca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias digicertglobalrootca -file digicertglobalrootca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias globalsignca -file globalsignca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias thawteprimaryrootca -file thawteprimaryrootca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias starfieldrootg2ca -file starfieldrootg2ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias geotrustglobalca -file geotrustglobalca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias soneraclass2ca -file soneraclass2ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias swisscomrootevca2 -file swisscomrootevca2.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias verisigntsaca -file verisigntsaca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias soneraclass1ca -file soneraclass1ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias quovadisrootca -file quovadisrootca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias affirmtrustpremiumeccca -file affirmtrustpremiumeccca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias starfieldservicesrootg2ca -file starfieldservicesrootg2ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias comodoaaaca -file comodoaaaca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias aolrootca2 -file aolrootca2.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias addtrustqualifiedca -file addtrustqualifiedca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias keynectisrootca -file keynectisrootca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias aolrootca1 -file aolrootca1.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias verisignclass2g3ca -file verisignclass2g3ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias addtrustexternalca -file addtrustexternalca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias luxtrustglobalrootca -file luxtrustglobalrootca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias verisignclass2g2ca -file verisignclass2g2ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias geotrustprimarycag3 -file geotrustprimarycag3.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias geotrustprimarycag2 -file geotrustprimarycag2.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias swisssigngoldg2ca -file swisssigngoldg2ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias entrust2048ca -file entrust2048ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias chunghwaepkirootca -file chunghwaepkirootca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias camerfirmachambersignca -file camerfirmachambersignca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias camerfirmachambersca -file camerfirmachambersca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias usertrusteccca -file usertrusteccca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias godaddyclass2ca -file godaddyclass2ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias affirmtrustpremiumca -file affirmtrustpremiumca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias usertrustrsaca -file usertrustrsaca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias verisignclass1g3ca -file verisignclass1g3ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias secomevrootca1 -file secomevrootca1.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias verisignclass1g2ca -file verisignclass1g2ca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias comodoeccca -file comodoeccca.cer
keytool -export -keystore cacerts -rfc -storepass changeit -alias godaddyrootg2ca -file godaddyrootg2ca.cer
pause