keytool -delete -keystore cacerts -storepass changeit -alias digicertassuredidrootca
keytool -delete -keystore cacerts -storepass changeit -alias comodorsaca
keytool -delete -keystore cacerts -storepass changeit -alias thawtepremiumserverca
keytool -delete -keystore cacerts -storepass changeit -alias swisssignplatinumg2ca
keytool -delete -keystore cacerts -storepass changeit -alias swisssignsilverg2ca
keytool -delete -keystore cacerts -storepass changeit -alias equifaxsecureebusinessca1
keytool -delete -keystore cacerts -storepass changeit -alias securetrustca
keytool -delete -keystore cacerts -storepass changeit -alias utnuserfirstclientauthemailca
keytool -delete -keystore cacerts -storepass changeit -alias affirmtrustnetworkingca
keytool -delete -keystore cacerts -storepass changeit -alias entrustevca
keytool -delete -keystore cacerts -storepass changeit -alias utnuserfirsthardwareca
keytool -delete -keystore cacerts -storepass changeit -alias globalsigneccrootcar5
keytool -delete -keystore cacerts -storepass changeit -alias globalsigneccrootcar4
keytool -delete -keystore cacerts -storepass changeit -alias certumca
keytool -delete -keystore cacerts -storepass changeit -alias addtrustclass1ca
keytool -delete -keystore cacerts -storepass changeit -alias entrustrootcag2
keytool -delete -keystore cacerts -storepass changeit -alias equifaxsecureca
keytool -delete -keystore cacerts -storepass changeit -alias quovadisrootca3
keytool -delete -keystore cacerts -storepass changeit -alias quovadisrootca2
keytool -delete -keystore cacerts -storepass changeit -alias swisscomrootca2
keytool -delete -keystore cacerts -storepass changeit -alias digicerthighassuranceevrootca
keytool -delete -keystore cacerts -storepass changeit -alias equifaxsecureglobalebusinessca1
keytool -delete -keystore cacerts -storepass changeit -alias geotrustuniversalca
keytool -delete -keystore cacerts -storepass changeit -alias verisignclass3ca
keytool -delete -keystore cacerts -storepass changeit -alias thawteprimaryrootcag3
keytool -delete -keystore cacerts -storepass changeit -alias thawteprimaryrootcag2
keytool -delete -keystore cacerts -storepass changeit -alias deutschetelekomrootca2
keytool -delete -keystore cacerts -storepass changeit -alias buypassclass3ca
keytool -delete -keystore cacerts -storepass changeit -alias utnuserfirstobjectca
keytool -delete -keystore cacerts -storepass changeit -alias geotrustprimaryca
keytool -delete -keystore cacerts -storepass changeit -alias buypassclass2ca
keytool -delete -keystore cacerts -storepass changeit -alias baltimorecodesigningca
keytool -delete -keystore cacerts -storepass changeit -alias verisignclass1ca
keytool -delete -keystore cacerts -storepass changeit -alias baltimorecybertrustca
keytool -delete -keystore cacerts -storepass changeit -alias starfieldclass2ca
keytool -delete -keystore cacerts -storepass changeit -alias actalisauthenticationrootca
keytool -delete -keystore cacerts -storepass changeit -alias camerfirmachamberscommerceca
keytool -delete -keystore cacerts -storepass changeit -alias ttelesecglobalrootclass3ca
keytool -delete -keystore cacerts -storepass changeit -alias verisignclass3g5ca
keytool -delete -keystore cacerts -storepass changeit -alias ttelesecglobalrootclass2ca
keytool -delete -keystore cacerts -storepass changeit -alias verisignclass3g4ca
keytool -delete -keystore cacerts -storepass changeit -alias verisignclass3g3ca
keytool -delete -keystore cacerts -storepass changeit -alias xrampglobalca
keytool -delete -keystore cacerts -storepass changeit -alias entrustrootcaec1
keytool -delete -keystore cacerts -storepass changeit -alias certplusclass3pprimaryca
keytool -delete -keystore cacerts -storepass changeit -alias certumtrustednetworkca
keytool -delete -keystore cacerts -storepass changeit -alias verisignclass3g2ca
keytool -delete -keystore cacerts -storepass changeit -alias globalsignr3ca
keytool -delete -keystore cacerts -storepass changeit -alias utndatacorpsgcca
keytool -delete -keystore cacerts -storepass changeit -alias secomscrootca2
keytool -delete -keystore cacerts -storepass changeit -alias gtecybertrustglobalca
keytool -delete -keystore cacerts -storepass changeit -alias secomscrootca1
keytool -delete -keystore cacerts -storepass changeit -alias affirmtrustcommercialca
keytool -delete -keystore cacerts -storepass changeit -alias verisignuniversalrootca
keytool -delete -keystore cacerts -storepass changeit -alias globalsignr2ca
keytool -delete -keystore cacerts -storepass changeit -alias certplusclass2primaryca
keytool -delete -keystore cacerts -storepass changeit -alias digicertglobalrootca
keytool -delete -keystore cacerts -storepass changeit -alias globalsignca
keytool -delete -keystore cacerts -storepass changeit -alias thawteprimaryrootca
keytool -delete -keystore cacerts -storepass changeit -alias starfieldrootg2ca
keytool -delete -keystore cacerts -storepass changeit -alias geotrustglobalca
keytool -delete -keystore cacerts -storepass changeit -alias soneraclass2ca
keytool -delete -keystore cacerts -storepass changeit -alias swisscomrootevca2
keytool -delete -keystore cacerts -storepass changeit -alias verisigntsaca
keytool -delete -keystore cacerts -storepass changeit -alias soneraclass1ca
keytool -delete -keystore cacerts -storepass changeit -alias quovadisrootca
keytool -delete -keystore cacerts -storepass changeit -alias affirmtrustpremiumeccca
keytool -delete -keystore cacerts -storepass changeit -alias starfieldservicesrootg2ca
keytool -delete -keystore cacerts -storepass changeit -alias comodoaaaca
keytool -delete -keystore cacerts -storepass changeit -alias aolrootca2
keytool -delete -keystore cacerts -storepass changeit -alias addtrustqualifiedca
keytool -delete -keystore cacerts -storepass changeit -alias keynectisrootca
keytool -delete -keystore cacerts -storepass changeit -alias aolrootca1
keytool -delete -keystore cacerts -storepass changeit -alias verisignclass2g3ca
keytool -delete -keystore cacerts -storepass changeit -alias addtrustexternalca
keytool -delete -keystore cacerts -storepass changeit -alias luxtrustglobalrootca
keytool -delete -keystore cacerts -storepass changeit -alias verisignclass2g2ca
keytool -delete -keystore cacerts -storepass changeit -alias geotrustprimarycag3
keytool -delete -keystore cacerts -storepass changeit -alias geotrustprimarycag2
keytool -delete -keystore cacerts -storepass changeit -alias swisssigngoldg2ca
keytool -delete -keystore cacerts -storepass changeit -alias entrust2048ca
keytool -delete -keystore cacerts -storepass changeit -alias chunghwaepkirootca
keytool -delete -keystore cacerts -storepass changeit -alias camerfirmachambersignca
keytool -delete -keystore cacerts -storepass changeit -alias camerfirmachambersca
keytool -delete -keystore cacerts -storepass changeit -alias usertrusteccca
keytool -delete -keystore cacerts -storepass changeit -alias godaddyclass2ca
keytool -delete -keystore cacerts -storepass changeit -alias affirmtrustpremiumca
keytool -delete -keystore cacerts -storepass changeit -alias usertrustrsaca
keytool -delete -keystore cacerts -storepass changeit -alias verisignclass1g3ca
keytool -delete -keystore cacerts -storepass changeit -alias secomevrootca1
keytool -delete -keystore cacerts -storepass changeit -alias verisignclass1g2ca
keytool -delete -keystore cacerts -storepass changeit -alias comodoeccca
keytool -delete -keystore cacerts -storepass changeit -alias godaddyrootg2ca
pause