@REM keytool -delete -keystore cacerts -storepass changeit -alias digicertassuredidrootca
@REM keytool -delete -keystore cacerts -storepass changeit -alias comodorsaca
@REM keytool -delete -keystore cacerts -storepass changeit -alias thawtepremiumserverca
@REM keytool -delete -keystore cacerts -storepass changeit -alias swisssignplatinumg2ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias swisssignsilverg2ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias equifaxsecureebusinessca1
@REM keytool -delete -keystore cacerts -storepass changeit -alias securetrustca
@REM keytool -delete -keystore cacerts -storepass changeit -alias utnuserfirstclientauthemailca
@REM keytool -delete -keystore cacerts -storepass changeit -alias affirmtrustnetworkingca
@REM keytool -delete -keystore cacerts -storepass changeit -alias entrustevca
@REM keytool -delete -keystore cacerts -storepass changeit -alias utnuserfirsthardwareca
@REM keytool -delete -keystore cacerts -storepass changeit -alias globalsigneccrootcar5
@REM keytool -delete -keystore cacerts -storepass changeit -alias globalsigneccrootcar4
@REM keytool -delete -keystore cacerts -storepass changeit -alias certumca
@REM keytool -delete -keystore cacerts -storepass changeit -alias addtrustclass1ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias entrustrootcag2
@REM keytool -delete -keystore cacerts -storepass changeit -alias equifaxsecureca
@REM keytool -delete -keystore cacerts -storepass changeit -alias quovadisrootca3
@REM keytool -delete -keystore cacerts -storepass changeit -alias quovadisrootca2
@REM keytool -delete -keystore cacerts -storepass changeit -alias swisscomrootca2
@REM keytool -delete -keystore cacerts -storepass changeit -alias digicerthighassuranceevrootca
@REM keytool -delete -keystore cacerts -storepass changeit -alias equifaxsecureglobalebusinessca1
@REM keytool -delete -keystore cacerts -storepass changeit -alias geotrustuniversalca
@REM keytool -delete -keystore cacerts -storepass changeit -alias verisignclass3ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias thawteprimaryrootcag3
@REM keytool -delete -keystore cacerts -storepass changeit -alias thawteprimaryrootcag2
@REM keytool -delete -keystore cacerts -storepass changeit -alias deutschetelekomrootca2
@REM keytool -delete -keystore cacerts -storepass changeit -alias buypassclass3ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias utnuserfirstobjectca
@REM keytool -delete -keystore cacerts -storepass changeit -alias geotrustprimaryca
@REM keytool -delete -keystore cacerts -storepass changeit -alias buypassclass2ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias baltimorecodesigningca
@REM keytool -delete -keystore cacerts -storepass changeit -alias verisignclass1ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias baltimorecybertrustca
@REM keytool -delete -keystore cacerts -storepass changeit -alias starfieldclass2ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias actalisauthenticationrootca
@REM keytool -delete -keystore cacerts -storepass changeit -alias camerfirmachamberscommerceca
@REM keytool -delete -keystore cacerts -storepass changeit -alias ttelesecglobalrootclass3ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias verisignclass3g5ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias ttelesecglobalrootclass2ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias verisignclass3g4ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias verisignclass3g3ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias xrampglobalca
@REM keytool -delete -keystore cacerts -storepass changeit -alias entrustrootcaec1
@REM keytool -delete -keystore cacerts -storepass changeit -alias certplusclass3pprimaryca
@REM keytool -delete -keystore cacerts -storepass changeit -alias certumtrustednetworkca
@REM keytool -delete -keystore cacerts -storepass changeit -alias verisignclass3g2ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias globalsignr3ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias utndatacorpsgcca
@REM keytool -delete -keystore cacerts -storepass changeit -alias secomscrootca2
@REM keytool -delete -keystore cacerts -storepass changeit -alias gtecybertrustglobalca
@REM keytool -delete -keystore cacerts -storepass changeit -alias secomscrootca1
@REM keytool -delete -keystore cacerts -storepass changeit -alias affirmtrustcommercialca
@REM keytool -delete -keystore cacerts -storepass changeit -alias verisignuniversalrootca
@REM keytool -delete -keystore cacerts -storepass changeit -alias globalsignr2ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias certplusclass2primaryca
@REM keytool -delete -keystore cacerts -storepass changeit -alias digicertglobalrootca
@REM keytool -delete -keystore cacerts -storepass changeit -alias globalsignca
@REM keytool -delete -keystore cacerts -storepass changeit -alias thawteprimaryrootca
@REM keytool -delete -keystore cacerts -storepass changeit -alias starfieldrootg2ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias geotrustglobalca
@REM keytool -delete -keystore cacerts -storepass changeit -alias soneraclass2ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias swisscomrootevca2
@REM keytool -delete -keystore cacerts -storepass changeit -alias verisigntsaca
@REM keytool -delete -keystore cacerts -storepass changeit -alias soneraclass1ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias quovadisrootca
@REM keytool -delete -keystore cacerts -storepass changeit -alias affirmtrustpremiumeccca
@REM keytool -delete -keystore cacerts -storepass changeit -alias starfieldservicesrootg2ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias comodoaaaca
@REM keytool -delete -keystore cacerts -storepass changeit -alias aolrootca2
@REM keytool -delete -keystore cacerts -storepass changeit -alias addtrustqualifiedca
@REM keytool -delete -keystore cacerts -storepass changeit -alias keynectisrootca
@REM keytool -delete -keystore cacerts -storepass changeit -alias aolrootca1
@REM keytool -delete -keystore cacerts -storepass changeit -alias verisignclass2g3ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias addtrustexternalca
@REM keytool -delete -keystore cacerts -storepass changeit -alias luxtrustglobalrootca
@REM keytool -delete -keystore cacerts -storepass changeit -alias verisignclass2g2ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias geotrustprimarycag3
@REM keytool -delete -keystore cacerts -storepass changeit -alias geotrustprimarycag2
@REM keytool -delete -keystore cacerts -storepass changeit -alias swisssigngoldg2ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias entrust2048ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias chunghwaepkirootca
@REM keytool -delete -keystore cacerts -storepass changeit -alias camerfirmachambersignca
@REM keytool -delete -keystore cacerts -storepass changeit -alias camerfirmachambersca
@REM keytool -delete -keystore cacerts -storepass changeit -alias usertrusteccca
@REM keytool -delete -keystore cacerts -storepass changeit -alias godaddyclass2ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias affirmtrustpremiumca
@REM keytool -delete -keystore cacerts -storepass changeit -alias usertrustrsaca
@REM keytool -delete -keystore cacerts -storepass changeit -alias verisignclass1g3ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias secomevrootca1
@REM keytool -delete -keystore cacerts -storepass changeit -alias verisignclass1g2ca
@REM keytool -delete -keystore cacerts -storepass changeit -alias comodoeccca
@REM keytool -delete -keystore cacerts -storepass changeit -alias godaddyrootg2ca
pause